export const PRODUCT_REQUEST_SEND="PRODUCT_REQUEST_SEND"
export const PRODUCT_REQUEST_SUCCESS="PRODUCT_REQUEST_SUCCESS"
export const PRODUCT_REQUEST_FAILED="PRODUCT_REQUEST_FAILED"
export const SEARCH_PRODUCT="SEARCH_PRODUCT"

export const PRODUCT_DETAILS_REQUEST_SEND="PRODUCT_DETAILS_REQUEST_SEND"
export const PRODUCT_DETAILS_REQUEST_SUCCESS="PRODUCT_DETAILS_REQUEST_SUCCESS"
export const PRODUCT_DETAILS_REQUEST_FAILED="PRODUCT_DETAILS_REQUEST_FAILED"

export const ADD_TO_CART="ADD_TO_CART"
export const ADD_TO_CART_REQUEST_SEND="ADD_TO_CART_REQUEST_SEND"
export const ADD_TO_CART_REQUEST_SUCCESS="ADD_TO_CART_REQUEST_SUCCESS"
export const ADD_TO_CART_REQUEST_FAILED="ADD_TO_CART_REQUEST_FAILED"
export const CART_ITEMS_RESET="CART_ITEMS_RESET"

export const FETCH_CART_ITEMS="FETCH_CART_ITEMS"
export const FETCH_CART_ITEMS_REQUEST="FETCH_CART_ITEMS_REQUEST"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"

export const LOGIN_REQUEST_SEND="LOGIN_REQUEST_SEND"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const LOGOUT="LOGOUT"

export const REGISTER_REQUEST_SEND="REGISTER_REQUEST_SEND"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"

export const USER_DETAILS_REQUEST="USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS="USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAILED="USER_DETAILS_FAILED"
export const USER_DETAILS_RESET="USER_DETAILS_RESET"

export const USER_DETAILS_UPDATE_REQUEST="USER_DETAILS_UPDATE_REQUEST"
export const USER_DETAILS_UPDATE_SUCCESS="USER_DETAILS_UPDATE_SUCCESS"
export const USER_DETAILS_UPDATE_FAILED="USER_DETAILS_UPDATE_FAILED"

export const SHIPPING_REQUEST_SEND="SHIPPING_REQUEST_SEND"
export const SHIPPING_REQUEST_SUCCESS="SHIPPING_REQUEST_SUCCESS"
export const SHIPPING_REQUEST_FAILED="SHIPPING_REQUEST_FAILED"

export const SET_PAYMENT_METHOD="SET_PAYMENT_METHOD"

export const PLACE_ORDER_REQUEST="PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS="PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAILED="PLACE_ORDER_FAILED"

export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED="ORDER_DETAILS_FAILED"
export const ORDER_DETAILS_RESET="ORDER_DETAILS_RESET"



export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAILED="ORDER_PAY_FAILED"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"

export const ADD_REVIEW_REQUEST="ADD_REVIEW_REQUEST"
export const ADD_REVIEW_SUCCESS="ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAILED="ADD_REVIEW_FAILED"
export const ADD_REVIEW_RESET="ADD_REVIEW_RESET"

export const ORDER_DELIVER_REQUEST="ORDER_DELIVER_REQUEST"
export const ORDER_DELIVER_SUCCESS="ORDER_DELIVER_SUCCESS"
export const ORDER_DELIVER_FAILED="ORDER_DELIVER_FAILED"
export const ORDER_DELIVER_RESET="ORDER_DELIVER_RESET"

export const SHOW_MY_ORDERS_REQUEST="SHOW_MY_ORDERS_REQUEST"
export const SHOW_MY_ORDERS_SUCCESS="SHOW_MY_ORDERS_SUCCESS"
export const SHOW_MY_ORDERS_FAILED="SHOW_MY_ORDERS_FAILED"
export const SHOW_MY_ORDERS_RESET="SHOW_MY_ORDERS_RESET"

export const USERS_LIST_REQUEST="USERS_LIST_REQUEST"
export const USERS_LIST_SUCCESS="USERS_LIST_SUCCESS"
export const USERS_LIST_FAILED="USERS_LIST_FAILED"
export const USERS_LIST_RESET="USERS_LIST_RESET"

export const ORDERS_LIST_REQUEST="ORDERS_LIST_REQUEST"
export const ORDERS_LIST_SUCCESS="ORDERS_LIST_SUCCESS"
export const ORDERS_LIST_FAILED="ORDERS_LIST_FAILED"
export const ORDERS_LIST_RESET="ORDERS_LIST_RESET"


export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED="DELETE_USER_FAILED"


export const DELETE_PRODUCT_REQUEST="DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILED="DELETE_PRODUCT_FAILED"

export const CREATE_PRODUCT_REQUEST="CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS="CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILED="CREATE_PRODUCT_FAILED"
export const CREATE_PRODUCT_RESET="CREATE_PRODUCT_RESET"

export const FIND_USER_TO_EDIT_REQUEST="FIND_USER_TO_EDIT_REQUEST"
export const FIND_USER_TO_EDIT_SUCCESS="FIND_USER_TO_EDIT_SUCCESS"
export const FIND_USER_TO_EDIT_FAILED="FIND_USER_TO_EDIT_FAILED"

export const EDIT_USER_AND_UPDATE_REQUEST="EDIT_USER_AND_UPDATE_REQUEST"
export const EDIT_USER_AND_UPDATE_SUCCESS="EDIT_USER_AND_UPDATE_SUCCESS"
export const EDIT_USER_AND_UPDATE_FAILED="EDIT_USER_AND_UPDATE_FAILED"
export const EDIT_USER_AND_UPDATE_RESET="EDIT_USER_AND_UPDATE_RESET"

export const FIND_PRODUCT_TO_EDIT_REQUEST="FIND_PRODUCT_TO_EDIT_REQUEST"
export const FIND_PRODUCT_TO_EDIT_SUCCESS="FIND_PRODUCT_TO_EDIT_SUCCESS"
export const FIND_PRODUCT_TO_EDIT_FAILED="FIND_PRODUCT_TO_EDIT_FAILED"

export const EDIT_PRODUCT_AND_UPDATE_REQUEST="EDIT_PRODUCT_AND_UPDATE_REQUEST"
export const EDIT_PRODUCT_AND_UPDATE_SUCCESS="EDIT_PRODUCT_AND_UPDATE_SUCCESS"
export const EDIT_PRODUCT_AND_UPDATE_FAILED="EDIT_PRODUCT_AND_UPDATE_FAILED"
export const EDIT_PRODUCT_AND_UPDATE_RESET="EDIT_PRODUCT_AND_UPDATE_RESET"


export const PRODUCT_SEARCH_REQUEST="PRODUCT_SEARCH_REQUEST"
export const PRODUCT_SEARCH_SUCCESS="PRODUCT_SEARCH_SUCCESS"
export const PRODUCT_SEARCH_FAILED="PRODUCT_SEARCH_FAILED"